### ISSUE TITLE
Change to beta version of XIVAPI

### ISSUE THREAD

**Issue by gnbezerra** [catgirl-jade/nophicas-tidings#9]
Currently, all requests to https://xivapi.com/search are failing with an HTTP 500:
```json
{
    "Error": true,
    "Subject": "XIVAPI ERROR",
    "Note": "Get on discord: https:\/\/discord.gg\/MFFVHWC",
    "Message": "Search Error: No alive nodes found in your cluster",
    "Hash": "baa4b97efdd20335fe561bdf15e99f1f6a8f088b",
    "Ex": "App\\Common\\Exceptions\\SearchException",
    "ExCode": 500,
    "Url": "",
    "Debug": {
        "ID": "binGhFek24092412",
        "File": "#55 xivapi.com\/src\/Controller\/SearchController.php",
        "Method": "POST",
        "Path": "\/search",
        "Action": "App\\Controller\\SearchController::search",
        "Code": 500,
        "Date": "2024-09-24 12:04:05",
        "Env": "prod"
    }
}
```

The current version of XIVAPI was [deprecated](https://discord.com/channels/474518001173921794/557164349714726932/1221396202428432424) due to using outdated sources and being a hell to maintain, and Miu now [recommends using his new beta version](https://discord.com/channels/474518001173921794/557164349714726932/1252303059342852097): https://beta.xivapi.com/.

The servers for the outdated version are down and, apparently, they are not making much effort to re-up them.

**Comment by catgirl-jade** [comment]
Sorry for late on this, have been very busy. Let me see what I can do

**Comment by catgirl-jade** [comment]
Finally got around to this, it should be fixed. TYSM for bringing this to my attention!
